### ISSUE TITLE
[Add to wiki] Skidmark documentation

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigsofrods.github.io#1]
Request to add a documentation about skidmarks to the terrn description file.

Here's how I added them to a terrain:
into -groundmodel.cfg:

[asphalt]
strength = 1.1
adhesion velocity = 3.0
static friction coefficient = 1.1
sliding friction coefficient = 0.7
hydrodynamic friction = 0.01
stribeck velocity = 6

into the .odef files of the meshes which should have skidmarks

stdfriction asphalt

**Comment by Max98** [comment]
Skidmarks are automatically added if tarmac/asphalt is found in the terrain. So this is more of how to add asphalt/tarmac to the terrain using the landuse mapping.

**Comment by Hiradur** [comment]
Closing as we are going to remove the docs section from the static site and keep the old wiki

@DirtGamer301 would be great if you include this on the wiki

**Comment by DirtGamer301** [comment]
http://www.rigsofrods.com/wiki/index.php?title=Groundmodel_Description_File&action=submit

The default types are: concrete, asphalt, gravel, rock, ice, snow, metal, grass, sand and mud. Using an asphalt groundmodel will automatically add skidmarks. 


Is this everything to add? I sadly don't know much about terrains so...
