### ISSUE TITLE
[Add to wiki] AI documentation

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigsofrods.github.io#2]
Maybe that's something to add later, as AI is still very WIP (I think).

Just probably create a wiki page about all the AI stuff and what to add to make it work with your own terrain.

**Comment by gigapouch** [comment]
Yea, I'd like to learn how to make my own AI cars too.

**Comment by DirtGamer301** [comment]
AI maps*
I pretty much managed to somehow do it with MitCity, but idk how. I don't even know what I did, I think at the end I just placed the buildings of MitCity on the AI police chase Flatmap.
I have some wild guesses how to add all the stuff, but as I struggled with the police chase on MitCity, and didn't manage adding it to NeoQueretaro by doing the following, and many others want to do it, too, I think a wiki documenatation would be good :)

How I tried it (I think);
Make sure the vehicle you want to be cop car uses a GUID, otherwise add it.
Add this to the .tobj:
2400, 2.973937, 2178, 0, 0, 0, truck *truck name*.truck
^spawn point of the police car

Add to the end of the .terrn2:
[Scripts]
PolicePursuit.as=

In the script/ .as file:

			game.message("You need the *vehicle* for this map to work!!! Check Angelscript.log for more info.","note.png", 100000, true);
			game.log("You need the *vehicle* for this map to work !!!");
			game.log("Link: *link");

*means you have to replace it with the correct stuff*


I think that was it.

**Comment by gigapouch** [comment]
It would be nice though, if the AI could be set to follow the road randomly like in BeamNG. You could just select the road texture in-game and RoR could do the rest.

**Comment by Hiradur** [comment]
As this is just one aspect of the AngelScript API, it should only be a subsection of a site about the AS API. For now, https://github.com/RigsOfRods/rigs-of-rods/tree/master/doc/angelscript should provide enough info (though, it seems, the AI is missing) for someone to start a wiki page.

Closing as we are going to remove the docs section from the static site and keep the old wiki
