### ISSUE TITLE
Main Page load extremely slow

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigsofrods.github.io#4]
It takes me nearly 2 min to load rigsofrods.github.io on Edge and 30 s on Firefox nighlty x64.
And no, my internet or PC isn't slow!

**Comment by DirtGamer301** [comment]
I just tested, it was 1 min 10 seconds here right now, and I don't have bad internet either. But Firefox. Artem said it'll work well with "Chrome based  webbrowsers".
I'm on PC.

**Comment by Speciesx** [comment]
lol?
The page should work well at least on the 3 main browsers Chrome, Firefox and MS (IE and Edge).

**Comment by Hiradur** [comment]
This is due to the WebP image decoder running in Javascript on non-Chrome based browsers. We have to replace all screenshots with .jpg pictures. Entries, anyone?

**Comment by Hiradur** [comment]
fixed, screenshots are still welcome though

**Comment by DirtGamer301** [comment]
We should ask some people with knowledge in screenshot taking like Fastedy (just an example) for this to take some screenshots for this on prupose.
