### ISSUE TITLE
Documentation wasting space and bad to maintain

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigsofrods.github.io#5]
I personally dislike the new Documentation area complete. The old on wiki based style definitely the better style here.
First of all it wasted extreme space, compared to the old wiki it need two times more room to show the same amount of information. Also the access to edit or create new articles is limited. 

Old wiki style vs new.

![1](https://cloud.githubusercontent.com/assets/1196375/9477552/72237c2a-4b73-11e5-8e2e-17895f5b793c.PNG)

![2](https://cloud.githubusercontent.com/assets/1196375/9477554/72f2b63e-4b73-11e5-9b7c-d63af79f1a57.PNG)

**Comment by Hiradur** [comment]
We'll keep the old wiki and remove the docs from the static site
